name: CI
on:
  push:
    branches:
      - '*'
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        #run: mkdir -p `${GITHUB_REPOSITORY##*/}_${GITHUB_REPOSITORY##*/}`
        run: echo $REPO_NAME
        env:
          REPO_NAME: "${GITHUB_REPOSITORY##*/}"
          
