name: CI
on:
  push:
    branches:
      - '*'
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: mkdir "${GITHUB_REPOSITORY##*/}"_"${GITHUB_REPOSITORY##*/}"  touch test
