name: CI
on:
  push:
    branches:
      - '*'
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        #run: echo "running on branch $BRANCH_NAME and repo name is $REPO_NAME"
        run: mkdir ${GITHUB_REPOSITORY##*/} && cd ${GITHUB_REPOSITORY##*/} && touch test
        #env:
         # REPO_NAME: ${GITHUB_REPOSITORY##*/}
          #BRANCH_NAME: ${GITHUB_REF##*/}
