name: CI
on:
  push:
    branches:
      - '*'
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        #run: echo running on branch $BRANCH_NAME and repo name is $${GITHUB_REPOSITORY##*/}
    env:
      REPO_NAME: ${GITHUB_REPOSITORY##*/}
      BRANCH_NAME: ${GITHUB_REF##*/}
