name: CI
on:
  push:
    branches:
      - '*'
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run:  |
              echo `GITHUB_REPOSITORY` 
              mkdir -p /opt/`GITHUB_REPOSITORY` 
              cd /opt/$GITHUB_REPOSITORY
              touch test 
              ls
          
