name: CI
on:
  push:
    branches:
      - '*'
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/} and repo name is ${GITHUB_REPOSITORY	}
