name: Stage1 CD
on:
  push:
    branches:
      - 'stage'
jobs:
  branch-name:
    runs-on: self-hosted
    steps:
      - name: Get Repo Branch Name
        run: echo running on branch ${GITHUB_REF##*\/} and repo name is ${GITHUB_REPOSITORY##*\/}
      - name: Create Directory base on repo and branch name
        run: | 
            mkdir -p /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            cd /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            pwd  
            echo "github action CD pipeline finsh" > github_action
