name: Stage1 CD
on:
  push:
    branches:
      - 'stage'
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo Branch Name
        run: echo running on branch ${Bra_Name} and repo name is ${Repo_Name}
      - name: Create Directory base on repo and branch name
        run: | 
            mkdir -p /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            cd /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            pwd   
        env: 
          Bra_Name: 'GITHUB_REF##*/'
          Repo_Name: 'GITHUB_REPOSITORY##*/'
