name: Stage1 CD
on:
  push:
    branches:
      - 'stage1'
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}  test
