name: Stage1 CD
on:
  push:
    branches:
      - '*'
jobs:
  branch-name:
    runs-on: self-hosted
    steps:
      - name: Get Repo Branch Name
        run: echo running on branch ${GITHUB_REF##*\/} and repo name is ${GITHUB_REPOSITORY##*\/}
      - name: Create Directory base on repo and branch name
        continue-on-error: true
        run: | 
            #git clone -b ${GITHUB_REF##*\/} --single-branch https://github.com/AliDevOpos/Dev.git /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}/
            ssh ${{ secrets.USER }}@${{ secrets.IP_ADDR }} -p ${{ secrets.SSH_PORT }}  "git -C /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}/ pull"
            #${{ secrets.GIT_PULL }}
      - name: restart odoo service
        run: |
            if [[ ${GITHUB_REF##*\/} == dev* ]] ; then ${{ secrets.RESTART_DEV_SERVICE }} ; fi
            if [[ ${GITHUB_REF##*\/} == preprod* ]] ; then ${{ secrets.RESTART_PREPROD_SERVICE }} ; fi
            if [[ ${GITHUB_REF##*\/} == master ]] ; then ${{ secrets.RESTART_PROD_SERVICE }}; else echo "no service need to restart"; fi
            
