name: Stage1 CD
on:
  push:
    branches:
      - '*'
jobs:
  branch-name:
    runs-on: self-hosted
    steps:
      - name: Get Repo Branch Name
        run: echo running on branch ${GITHUB_REF##*\/} and repo name is ${GITHUB_REPOSITORY##*\/}
      - name: Create Directory base on repo and branch name
        continue-on-error: true
        run: | 
            #git clone -b ${GITHUB_REF##*\/} --single-branch https://github.com/AliDevOpos/Dev.git /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            #mkdir -p /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            #cd /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            #pwd  
            #echo "github action CD pipeline finsh" > github_action
            #echo "finshed"
            ${{ secrets.GIT_PULL }}
      - name: restart dev service 
        if:  ${{ github.ref## }} == 'dev_stage'
        run: echo "restart dev service"

      - name: start stage1 sage1 serivce
        if:  ( '${GITHUB_REF##*\/}' == 'preprod_*' )
        run: echo "start preprod service on server"
