name: Stage1 CD
on:
  push:
    branches:
      - '*'
jobs:
  branch-name:
    runs-on: self-hosted
    steps:
      - name: Get Repo Branch Name
        run: echo running on branch ${GITHUB_REF##*\/} and repo name is ${GITHUB_REPOSITORY##*\/}
      - name: Create Directory base on repo and branch name
        run: | 
            git clone -b ${GITHUB_REF##*\/} --single-branch https://github.com/AliDevOpos/Dev.git /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            #mkdir -p /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            #cd /opt/${GITHUB_REPOSITORY##*\/}_${GITHUB_REF##*\/}
            #pwd  
            #echo "github action CD pipeline finsh" > github_action
            #echo "finshed"
            ${{ secrets.GIT_PULL }}
      - name: restart dev service 
        if: startsWith(${{ 'GITHUB_REF##*\/' }}, 'dev')
        run: "echo start stage service"
      - name: start stage1 sage1 serivce
        if: startsWith(${{ 'GITHUB_REF##*\/' }}, 'preprod')
        run: "echo start stage1 service on server"
