name: Stage1 CD
on:
  push:
    branches:
      - 'stage'
jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/} and repo name is ${GITHUB_REPOSITORY##*/}
      - name: test command
        run: echo  "test command"

